language: python
python:
  - "3.8"
# command to install dependencies
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install -r requirements.txt
# command to build documentation
script:
  - docs/build-book.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  on:
    branch: master
