os: linux
dist: xenial

jobs:
  include:
  - language: python
    python: "3.8"
    addons:
      apt:
        packages:
        - pandoc
        - pandoc-citeproc
    install:
    - pip install -r requirements.txt
    script:
    - docs/build-book.py
  - language: rust
    rust: stable
    before_install: cd accelerate 
    cache: cargo

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  edge: true
  on:
    branch: master
