language: python
python:
  - "3.8"

jobs:
  include:
  - python: "3.8"
    addons:
      apt:
        packages:
        - pandoc
        - pandoc-citeproc
    install:
    - pip install -r requirements.txt
    script:
    - docs/build-book.py
  - rust: stable
    before_install: cd accelerate 
    cache: cargo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  on:
    branch: master
