num_signals = 30
num_responses = 16

output.expandvars = '$HOME/testrun'

[kde_estimate]
  size = 500
  signal.length = 5000

[signal]
  length = 50000

  components = ['S']

  [[signal.reactions]]
  k = 20.0 # kappa
  reactants = []
  products = ['S']

  [[signal.reactions]]
  k = 0.005 # lambda
  reactants = ['S']
  products = []

[response]
  length = 50000

  components = ['X']

  [[response.reactions]]
  k = 0.005 # rho
  reactants = ['S']
  products = ['S', 'X']

  [[response.reactions]]
  k = 0.02 # mu
  reactants = ['X']
  products = []
