num_signals = 5000
num_responses = 1000

output.expandvars = '$HOME/testrun'

[kde_estimate]
  size = 15_000
  signal.length = 4_000
  signal.initial = 4_000
  response.initial = 1_000

[signal]
  length = 50_000

  components = ['S']

  [[signal.reactions]]
  k = 20.0 # kappa
  reactants = []
  products = ['S']

  [[signal.reactions]]
  k = 0.005 # lambda
  reactants = ['S']
  products = []

[response]
  length = 50_000

  components = ['X']

  [[response.reactions]]
  k = 0.005 # rho
  reactants = ['S']
  products = ['S', 'X']

  [[response.reactions]]
  k = 0.02 # mu
  reactants = ['X']
  products = []
